name: Verify Human Identity

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clone Verified Agent Repo
        run: git clone https://github.com/BillionsNetwork/verified-agent-identity.git temp

      - name: Copy scripts
        run: mv temp/scripts ./scripts

      - name: Install dependencies
        run: |
          cd scripts
          npm install

      - name: Create Ethereum Identity
        run: node scripts/createNewEthereumIdentity.js

      - name: Link Human to Agent
        run: |
          node scripts/manualLinkHumanToAgent.js --challenge '{"name":"rydee41","description":"rydee41 AI Agent"}'
